format = """
[](#3B4252)\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[  ](fg:#33658A)\
"""

command_timeout = 5000
add_newline = true

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
substitutions = { "Documents" = "󰈙 ", "Downloads" = " ", "Music" = " ", "Pictures" = " " }

[conda]
detect_files = ["environment.yml", "conda.yaml"]
format = '[$symbol$environment](dimmed green) '

[c]
detect_files = ["*.c", "*.h"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[elixir]
detect_files = ["mix.exs"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[elm]
detect_files = ["elm.json"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[git_branch]
always_show_remote = true
symbol = ""
style = "bg:#4C566A"
format = '[$symbol $branch]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind]($style)'

[golang]
detect_files = ["go.mod"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[haskell]
detect_files = ["*.cabal", "stack.yaml"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[java]
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[julia]
detect_files = ["Project.toml", "Manifest.toml"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[nodejs]
detect_files = ["package.json"]
symbol = ""
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[nim]
detect_files = ["*.nim"]
symbol = " "
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[python]
detect_files = ["pyproject.toml", "requirements.txt", "Pipfile"]
style = "bg:#3B4252"
format = '[(\($virtualenv\))]($style)'

[rust]
detect_files = ["Cargo.toml"]
symbol = ""
style = "bg:#86BBD8"
format = '[$symbol($version)]($style)'

[docker_context]
detect_files = [".docker"]
symbol = " "
style = "bg:#06969A"
format = '[$symbol $context]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A"
format = '[ $time ]($style)'

